global:
  imageRegistry: swampupsec.jfrog.io
platform:
  version: 2.1.16
platformWebhook: {}
web:
  repository: swampupsec.jfrog.io/bookverse-web-internal-docker-release-local/web
  tag: 1.8.17
  replicas: 1
  port: 8080
  env:
    BOOKVERSE_ENV: DEV
    PLATFORM_BASE_URL: ''
    INVENTORY_BASE_URL: ''
    RECOMMENDATIONS_BASE_URL: /recommendations
    CHECKOUT_BASE_URL: /checkout
  ingress:
    enabled: true
    className: traefik
    host: bookverse.demo
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web
      traefik.ingress.kubernetes.io/redirect-to-https: 'false'
    tls:
      enabled: false
      secretName: ''
  service:
    type: ClusterIP
inventory:
  repository: swampupsec.jfrog.io/bookverse-inventory-internal-docker-release-local/inventory
  tag: 1.5.12
  replicas: 1
  port: 8000
recommendations:
  repository: swampupsec.jfrog.io/bookverse-recommendations-internal-docker-release-local/recommendations
  tag: 2.7.15
  replicas: 1
  port: 8000
  env:
    INVENTORY_BASE_URL: http://inventory
  cache:
    ttlSeconds: 60
  worker:
    enabled: true
    repository: swampupsec.jfrog.io/bookverse-recommendations-internal-docker-release-local/recommendations-worker
    tag: 1.8.23
    replicas: 1
    refreshSeconds: 60
  config:
    enabled: true
    mountPath: /app/config
    data:
      recommendations-settings.yaml: "weights:\n  genre: 1.0\n  author: 0.25\n  popularity:\
        \ 0.10\nlimits:\n  default: 10\n  max: 50\nfeatures:\n  filter_out_of_stock:\
        \ true\n  enable_cache: false\n  ttl_seconds: 60\n"
  resources:
    enabled: true
    mountPath: /app/resources
    data:
      stopwords.txt: 'the

        and

        of

        to

        a

        '
checkout:
  repository: swampupsec.jfrog.io/bookverse-checkout-internal-docker-release-local/checkout
  tag: 2.0.8
  replicas: 1
  port: 8000
  env:
    INVENTORY_BASE_URL: http://inventory
    REQUEST_TIMEOUT_SECONDS: '2'
    RETRY_ATTEMPTS: '2'
    PAYMENT_SUCCESS_RATIO: '1.0'
    LOG_LEVEL: INFO
